models/DocumentCategory.php
<?php

namespace diggindata\docvault\models;

use Yii;

/**
 * This is the model class for table "{{%category}}".
 *
 * @property integer $id
 * @property string $name
 *
 * @property Document[] $documents
 */
class DocumentCategory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dv_category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('docvault', 'ID (PK)'),
            'name' => Yii::t('docvault', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocuments()
    {
        return $this->hasMany(Document::className(), ['categoryId' => 'id']);
    }
}

controllers/DefaultController.php
<?php

namespace diggindata\docvault\controllers;

use yii\web\Controller;

class DefaultController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
}

controllers/DocumentCategoryController.php
<?php

namespace diggindata\docvault\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use diggindata\docvault\models\DocumentCategory;
use diggindata\docvault\models\DocumentCategorySearch;

/**
* DocumentCategoryController implements the CRUD actions for DocumentCategory model.
*/
class DocumentCategoryController extends Controller
{
    /*
	public function behaviors()
	{
		return [
			'access' => [ // {{{ 
				'class' => AccessControl::className(),
				//'only' => ['index','view','view-file','create','update','checkin','checkout','delete'],
				'rules' => [
					[
						'actions' => ['index','view','create','update','delete'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			], // }}} 
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}
    */

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view', 'create', 'update', 'delete'],
						'roles' => ['AppDocvaultFull', 'Administrator'],
					],
					[
						'allow' => true,
						'actions' => ['index', 'view'],
						'roles' => ['AppDocvaultView'],
					],
					[
						'allow' => true,
						'actions' => ['update', 'create', 'delete'],
						'roles' => ['AppDocvaultEdit'],
					],

				],
			],
		];
	}


	/**
	* Lists all DocumentCategory models.
	* @return mixed
	*/
	public function actionIndex()
	{
		$searchModel = new DocumentCategorySearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	* Displays a single DocumentCategory model.
	* @param integer $id
	* @return mixed
	*/
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	* Creates a new DocumentCategory model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	* @return mixed
	*/
	public function actionCreate()
	{
		$model = new DocumentCategory();

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->addFlash('success', Yii::t('docvault','The document category {name} has been created.', ['name'=>$model->name]));
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	/**
	* Updates an existing DocumentCategory model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->addFlash('success', Yii::t('docvault','The document category {name} has been updated.', ['name'=>$model->name]));
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	* Deletes an existing DocumentCategory model.
	* If deletion is successful, the browser will be redirected to the 'index' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect(['index']);
	}

	/**
	* Finds the DocumentCategory model based on its primary key value.
	* If the model is not found, a 404 HTTP exception will be thrown.
	* @param integer $id
	* @return DocumentCategory the loaded model
	* @throws NotFoundHttpException if the model cannot be found
	*/
	protected function findModel($id)
	{
		if (($model = DocumentCategory::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

controllers/DocumentController.php
<?php

namespace diggindata\docvault\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UnauthorizedHttpException;
use yii\web\UploadedFile;
use yii\base\Event;
use yii\web\Response;

use diggindata\docvault\models\Document;
use diggindata\docvault\models\DocumentPermissionsForm;
use diggindata\docvault\models\DocumentSearch;
use diggindata\docvault\models\Log;
use diggindata\docvault\models\Permission;
/**
* DocumentController implements the CRUD actions for Document model.
*/
class DocumentController extends Controller
{
	/*
	public function behaviors()
	{
	return [
	'access' => [ // {{{ 
	'class' => AccessControl::className(),
	//'only' => ['index','view','view-file','create','update','checkin','checkout','delete'],
	'rules' => [
	[
	'actions' => ['index','view','view-file','create','update','update-permissions','checkin','checkout','delete'],
	'allow' => true,
	'roles' => ['@'],
	],
	],
	], // }}} 
	'verbs' => [ // {{{ 
	'class' => VerbFilter::className(),
	'actions' => [
	'delete' => ['post'],
	],
	], // }}} 
	];
	}
	*/

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view', 'view-file', 'create', 'update', 'delete', 'checkout', 'checkin', 'update-permissions'],
						'roles' => ['AppDocvaultFull', 'Administrator'],
					],
					[
						'allow' => true,
						'actions' => ['index', 'view', 'view-file'],
						'roles' => ['AppDocvaultView'],
					],
					[
						'allow' => true,
						'actions' => ['update', 'create', 'checkout', 'checkin', 'update-permissions' ],
						'roles' => ['AppDocvaultEdit'],
					],

				],
			],
		];
	}

	/**
	* Lists all Document models.
	* @return mixed
	*/
	public function actionIndex()
	{
		$searchModel = new DocumentSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	* Displays a single Document model.
	* @param integer $id
	* @return mixed
	*/
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	* Downloads a single Document model.
	* @param integer $id
	* @return mixed
	*/
	public function actionViewFile($id)
	{
		$model = $this->findModel($id);
		if(!$model->mayView)
			throw new UnauthorizedHttpException(Yii::t('docvault','You don\'t have the permission to view the document {realname}.', ['realname'=>$model->realname]));

		$filename = Yii::getAlias($this->module->dataDir) . DIRECTORY_SEPARATOR . $model->id . '.dat';


		Yii::$app->response->sendFile($filename, rawurlencode($model->realname) )->send();

	}

	/**
	* Creates a new Document model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	* @return mixed
	*/
	public function actionCreate()
	{
		$model = new Document();
		if(!empty($_GET['Document'])) {
			$model->load(Yii::$app->request->get());
			unset($_GET['Document']);
		}

		if ($model->load(Yii::$app->request->post())) {
			$model->file = UploadedFile::getInstance($model, 'file');
			if($model->file) {
				$model->realname = $model->file->name;
				$model->mimeType = $model->file->type;
			}
			$isNewRecord = $model->isNewRecord;
			if ($model->file and $model->save()) {                
				// Save uploaded file
				$model->file->saveAs(Yii::getAlias($this->module->dataDir) . DIRECTORY_SEPARATOR . $model->id . '.dat');
				if ($isNewRecord) {
					// Create permissions for user on doc.
					$perm = new Permission;
					$perm->documentId = $model->id;
					$perm->userId = Yii::$app->user->id;
					$perm->rights = Permission::RIGHT_VIEW;
					$perm->save();
					$perm = new Permission;
					$perm->documentId = $model->id;
					$perm->userId = Yii::$app->user->id;
					$perm->rights = Permission::RIGHT_MODIFY;
					$perm->save();
				}
				Yii::$app->session->addFlash('success', Yii::t('docvault', 'The document {realname} has been created.', ['realname'=>$model->realname]));
				return $this->redirect(['view', 'id' => $model->id]);
			}
		} 
		return $this->render('create', [
			'model' => $model,
		]);
	}

	/**
	* Updates an existing Document model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);
		if($model->ownerId !== Yii::$app->user->id)
			throw new UnauthorizedHttpException(Yii::t('docvault','You are not the owner of the requested document {realname}.', ['realname'=>$model->realname]));
		if(!$model->mayModify)
			throw new UnauthorizedHttpException(Yii::t('docvault','You don\'t have the permission to modify the document {realname}.', ['realname'=>$model->realname]));
		if($model->status>0)
			throw new UnauthorizedHttpException(Yii::t('docvault','The requested document {realname} is currently checked out.', ['realname'=>$model->realname]));
		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->addFlash('success', Yii::t('docvault', 'The document {realname} has been updated.', ['realname'=>$model->realname]));
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	* Checks out a Document model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionCheckout($id)
	{
		$model = $this->findModel($id);
		if($model->status>0)
			throw new UnauthorizedHttpException('The requested document is currently checked out.');
		if (!$model->mayModify) 
			throw new UnauthorizedHttpException("You don't have 'Modify' permissions for this document.");

		$model->status = Yii::$app->user->id;
		$model->save();
		$realname = rawurlencode( $model->realname );
		// get the filename
		$filename = Yii::getAlias($this->module->dataDir) . DIRECTORY_SEPARATOR . $model->id . '.dat';

		Yii::$app->session->addFlash('success', Yii::t('docvault', 'The document {realname} has been checked out.', ['realname'=>$model->realname]));
		//Yii::$app->response->sendFile($filename, $realname )->send();
		return $this->render('view', ['model'=>$model]);

	}

	/**
	* Checks in a Document model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionCheckin($id)
	{
		$model = $this->findModel($id);
		if($model->status!==Yii::$app->user->id)
			throw new UnauthorizedHttpException('The requested document is currently checked out by another user.');
		$log = new Log();
		$log->documentId = $id;

		if ($log->load(Yii::$app->request->post())) {
			$log->file = UploadedFile::getInstance($log, 'file');
			if($log->file)
				$model->realname = $log->file->name;
			if ($log->file && $log->save()) {  
				$log->file->saveAs(Yii::getAlias($this->module->dataDir) . DIRECTORY_SEPARATOR . $model->id . '.dat');
				$model->status = 0;
				$model->save(false);
				Yii::$app->session->addFlash('success', Yii::t('docvault', 'The document {realname} has been checked in.', ['realname'=>$model->realname]));
				return $this->redirect(['view', 'id'=>$model->id]);
			}    
		} else {
			return $this->render('checkin', [
				'document' => $model,
				'model' => $log,
			]);
		}
	}

	public function actionUpdatePermissions($id)
	{
		$document = $this->findModel($id);
		// Is user the owner?
		if($document->ownerId !== Yii::$app->user->id)
			throw new UnauthorizedHttpException(Yii::t('docvault','You are not the owner of the requested document.'));
		// Is document not checked out?
		if($document->status>0)
			throw new UnauthorizedHttpException(Yii::t('docvault','The requested document is currently checked out.'));

		$permissions = Permission::find()->indexBy('id')->where(['documentId'=>$id])->all();

		$model = new DocumentPermissionsForm;

		$model->documentId = $id;
		foreach($permissions as $permission) {
			if($permission->rights==Permission::RIGHT_VIEW)
				$model->viewUsers[] = $permission->userId;
			elseif($permission->rights==Permission::RIGHT_MODIFY)
				$model->modifyUsers[] = $permission->userId;
		}

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$transaction = $this->module->db->beginTransaction();
			try {
				$permissions = $document->permissions;
				foreach($permissions as $permission)
					$permission->delete();
				foreach($model->viewUsers as $userId) {
					$permission = new Permission;
					$permission->documentId = $document->id;
					$permission->userId = $userId;
					$permission->rights = Permission::RIGHT_VIEW;
					if(!$permission->save())
						throw new \Exception('Error saving permission');
				}
				foreach($model->modifyUsers as $userId) {
					$permission = new Permission;
					$permission->documentId = $document->id;
					$permission->userId = $userId;
					$permission->rights = Permission::RIGHT_MODIFY;
					if(!$permission->save())
					throw new \Exception('Error saving permission');
				}
				$transaction->commit();
				Yii::$app->session->addFlash('success', Yii::t('docvault','The permissions have been updated.'));
				return $this->redirect(['view', 'id'=>$document->id]);
			} catch (\Exception $e) {
				$transaction->rollBack();
				return $this->render('updatePermissions', [
					'document'=>$document, 
					'model'=>$model, 
				]);        
			}
		} else {
			return $this->render('updatePermissions', [

views/document-category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DocumentCategory */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-category-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('docvault','Create') : Yii::t('docvault','Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/document-category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\DocumentCategory */

$this->title = Yii::t('docvault','Create New Document Category');
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault','Document Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="document-category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/document-category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentCategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('docvault','Document Categories');
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="document-category-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('docvault','Create New Document Category'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
		'pager' => [
			'class' => yii\widgets\LinkPager::className(),
			'firstPageLabel' => Yii::t('cruds', 'First'),
			'lastPageLabel' => Yii::t('cruds', 'Last'),
		],
		'filterModel' => $searchModel,
		'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
		'headerRowOptions' => ['class'=>'x'],
        'columns' => [
            ['class' => 'yii\grid\ActionColumn', 'template'=>'{view} {update} {delete}'],
            //'id',
            'name',
            [
                'label'=>Yii::t('docvault','Documents'),
                'format' => 'html',
                'value' => function ($model, $key, $index, $column) {
                    return Html::a(Yii::t('docvault', '{n, plural, =0{No documents} =1{One document} other{# documents}}', ['n' => count($model->documents)]), ['document/index', 'DocumentSearch[categoryId]'=>$model->id]);
                },
                'contentOptions' => ['style'=>'text-align:center'],
            ],
        ],
    ]); ?>

</div>

views/document-category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\DocumentCategory */

$this->title = 'Update Document Category: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => 'Document Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="document-category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/document-category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\DocumentCategory */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Document Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="document-category-view">

	<h1><?= Html::encode($this->title) ?></h1>

	<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('docvault', 'New Document'), ['document/create', 'Document[categoryId]' => $model->id], ['class' => 'btn btn-success']) ?>
	<?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('docvault', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
	<?= Html::a('<span class="glyphicon glyphicon-remove"></span> ' . Yii::t('docvault', 'Delete'), ['delete', 'id' => $model->id], [
		'class' => 'btn btn-danger',
		'data' => [
			'confirm' => 'Are you sure you want to delete this item?',
			'method' => 'post',
		],
	]) ?>

	<?= DetailView::widget([
		'model' => $model,
		'attributes' => [
			'id',
			'name',
			[
				'label' => Yii::t('docvault','Documents'),
				'format' => 'html',
				'value' => Html::a(count($model->documents), ['document/index', 'DocumentSearch[categoryId]'=>$model->id]),
			],
		],
	]) ?>

</div>