models/Document.php
<?php

namespace diggindata\docvault\models;

use Yii;
use yii\web\UploadedFile;
use \Da\User\Model\User;


/**
 * This is the model class for table "{{%document}}".
 *
 * @property integer $id
 * @property integer $categoryId
 * @property integer $ownerId
 * @property string $realname
 * @property string $mimeType
 * @property string $created
 * @property string $description
 * @property string $comment
 * @property integer $status
 *
 * @property Category $category
 */
class Document extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile file attribute
     */
    public $file;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dv_document}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['categoryId','description'], 'required'],
            [['ownerId', 'status'], 'integer'],
            [['categoryId','ownerId','realname'], 'required', 'on'=>['insert']],
            [['created'], 'safe'],
            [['comment'], 'string'],
            [['realname', 'mimeType', 'description'], 'string', 'max' => 255],
            [['file'], 'file', 'skipOnEmpty'=>false, 'on'=>'insert'],
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if($this->isNewRecord) {
                $this->ownerId = Yii::$app->user->id;
                $this->created = date('Y-m-d H:i:s');
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('docvault', 'ID'),
            'categoryId' => Yii::t('docvault', 'Category'),
            'ownerId' => Yii::t('docvault', 'Owner'),
            'realname' => Yii::t('docvault', 'Original File Name'),
            'mimeType' => Yii::t('docvault', 'Type'),
            'created' => Yii::t('docvault', 'Date First Checked-In'),
            'description' => Yii::t('docvault', 'Description of Contents'),
            'comment' => Yii::t('docvault', "Author's Note"),
            'status' => Yii::t('docvault', 'Checked out by'),
            'file' => Yii::t('docvault', 'Dokument'),
        ];
    }

    public function afterDelete()
    {
        parent::afterDelete();
        // delete file
        unlink(Yii::getAlias(Yii::$app->getModule('docvault')->dataDir) . DIRECTORY_SEPARATOR . $this->id . '.dat');

    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(DocumentCategory::className(), ['id' => 'categoryId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwnedByUser()
    {
        return $this->hasOne(User::className(), ['id' => 'ownerId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCheckedOutByUser()
    {
        return $this->hasOne(User::className(), ['id' => 'status']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLogs()
    {
        return $this->hasMany(Log::className(), ['documentId' => 'id'])->orderBy('modifiedOn DESC');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPermissions()
    {
        return $this->hasMany(Permission::className(), ['documentId' => 'id']);
    }

    public function getMayModify()
    {
        foreach($this->permissions as $permission) {
            if($permission->userId==Yii::$app->user->id and $permission->rights == Permission::RIGHT_MODIFY)
                return true;
            if($permission->userId==0 and $permission->rights == Permission::RIGHT_MODIFY)
                return true;
        }
        return false;
    }

    public function getMayView()
    {
        foreach($this->permissions as $permission) {
            if($permission->userId==Yii::$app->user->id and $permission->rights == Permission::RIGHT_VIEW)
                return true;
            if($permission->userId==0 and $permission->rights == Permission::RIGHT_VIEW)
                return true;
        }
        return false;
    }

}

models/Permission.php
<?php

namespace diggindata\docvault\models;

use Yii;
use Da\User\Model\User;

/**
 * This is the model class for table "{{%permission}}".
 *
 * @property integer $id
 * @property integer $documentId
 * @property integer $userId
 * @property integer $rights
 *
 * @property Document $document
 */
class Permission extends \yii\db\ActiveRecord
{
    Const RIGHT_VIEW = 1;
    Const RIGHT_MODIFY = 2;

    public $deleteMe;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dv_permission}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['documentId','userId','rights'], 'required'],
            [['documentId', 'userId', 'rights'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('docvault', 'ID (PK)'),
            'documentId' => Yii::t('docvault', 'Document'),
            'userId' => Yii::t('docvault', 'User'),
            'rights' => Yii::t('docvault', 'Rights'),
            'deleteMe' => Yii::t('docvault', 'Remove'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDocument()
    {
        return $this->hasOne(Document::className(), ['id' => 'documentId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public static function getRightsOptions()
    {
        return [
            self::RIGHT_VIEW => Yii::t('docvault', 'View'),
            self::RIGHT_MODIFY => Yii::t('docvault', 'Modify'),
        ];
    }
    
}

controllers/DefaultController.php
<?php

namespace diggindata\docvault\controllers;

use yii\web\Controller;

class DefaultController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
}

controllers/DocumentCategoryController.php
<?php

namespace diggindata\docvault\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use diggindata\docvault\models\DocumentCategory;
use diggindata\docvault\models\DocumentCategorySearch;

/**
* DocumentCategoryController implements the CRUD actions for DocumentCategory model.
*/
class DocumentCategoryController extends Controller
{
    /*
	public function behaviors()
	{
		return [
			'access' => [ // {{{ 
				'class' => AccessControl::className(),
				//'only' => ['index','view','view-file','create','update','checkin','checkout','delete'],
				'rules' => [
					[
						'actions' => ['index','view','create','update','delete'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			], // }}} 
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}
    */

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view', 'create', 'update', 'delete'],
						'roles' => ['AppDocvaultFull', 'Administrator'],
					],
					[
						'allow' => true,
						'actions' => ['index', 'view'],
						'roles' => ['AppDocvaultView'],
					],
					[
						'allow' => true,
						'actions' => ['update', 'create', 'delete'],
						'roles' => ['AppDocvaultEdit'],
					],

				],
			],
		];
	}


	/**
	* Lists all DocumentCategory models.
	* @return mixed
	*/
	public function actionIndex()
	{
		$searchModel = new DocumentCategorySearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	* Displays a single DocumentCategory model.
	* @param integer $id
	* @return mixed
	*/
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	* Creates a new DocumentCategory model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	* @return mixed
	*/
	public function actionCreate()
	{
		$model = new DocumentCategory();

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->addFlash('success', Yii::t('docvault','The document category {name} has been created.', ['name'=>$model->name]));
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	/**
	* Updates an existing DocumentCategory model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			Yii::$app->session->addFlash('success', Yii::t('docvault','The document category {name} has been updated.', ['name'=>$model->name]));
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	* Deletes an existing DocumentCategory model.
	* If deletion is successful, the browser will be redirected to the 'index' page.
	* @param integer $id
	* @return mixed
	*/
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect(['index']);
	}

	/**
	* Finds the DocumentCategory model based on its primary key value.
	* If the model is not found, a 404 HTTP exception will be thrown.
	* @param integer $id
	* @return DocumentCategory the loaded model
	* @throws NotFoundHttpException if the model cannot be found
	*/
	protected function findModel($id)
	{
		if (($model = DocumentCategory::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

views/document/_form.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

use diggindata\docvault\models\DocumentCategory;

/* @var $this yii\web\View */
/* @var $model app\models\Document */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="document-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'categoryId')->dropDownList(ArrayHelper::map(DocumentCategory::find()->all(), 'id', 'name'), array('prompt'=>Yii::t('docvault', '(Select)'))) ?>

    <?= '' //$form->field($model, 'ownerId')->textInput() ?>

    <?= '' // $form->field($model, 'realname')->textInput(['maxlength' => 255]) ?>

    <?= '' // $form->field($model, 'created')->textInput() ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

    <?= '' // $form->field($model, 'status')->textInput() ?>
    
    <?php if($model->isNewRecord) : ?>
    <?= $form->field($model, 'file')->fileInput() ?>
    <?php endif; ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('docvault', 'Create') : Yii::t('docvault', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/document/_logs.php
<?php
use yii\helpers\Html;
?>

<?= Yii::$app->timeZone ?>

<table class="table table-striped table-bordered">
    <thead>
        <th><?= Html::encode(Yii::t('docvault', 'User')) ?></th>
        <th><?= Html::encode(Yii::t('docvault', 'Check In Date')) ?></th>
        <th><?= Html::encode(Yii::t('docvault', 'Notes')) ?></th>
    </thead>
    <tbody>
        <?php foreach($model->logs as $log) : ?>
        <tr>
            <td><?= $log->user->username ?></td>
            <td><?= Yii::$app->formatter->asDatetime($log->modifiedOn .' '.'Europe/Berlin', 'medium') ?></td>
            <td><?= $log->note ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>


views/document/_meta.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
?>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'categoryId',
                'format' => 'html',
                'value' => Html::a($model->category->name, ['document-category/view', 'id'=>$model->categoryId]),
            ],
            [
                'attribute' => 'ownerId',
                'value' => $model->ownedByUser->username,
            ],
            'realname',
            'mimeType',
            [
                'attribute' => 'created',
                'value' => Yii::$app->formatter->asDatetime($model->created, 'medium'),
            ],
            'description',
            'comment:ntext',
            [
                'attribute' => 'status',
                'value' => !is_null($model->checkedOutByUser) ? $model->checkedOutByUser->username : Yii::t('docvault','(not yet)'),
            ],
        ],
    ]) ?>



views/document/_permissions.php
<?php
use yii\helpers\Html;
?>

<?php // yii\helpers\VarDumper::dump($model->permissions, 10, true); ?>

<table class="table table-striped table-bordered">
    <thead>
        <th><?= Html::encode(Yii::t('docvault', 'User')) ?></th>
        <th><?= Html::encode(Yii::t('docvault', 'Rights')) ?></th>
    </thead>
    <tbody>
        <?php foreach($model->permissions as $permission) : ?>
        <tr>
            <td><?= !is_null($permission->user) ? $permission->user->username : Yii::t('docvault','All Users') ?></td><td><?= /* $permission->rights . ' | ' . */ $permission->rightsOptions[$permission->rights] ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>


views/document/_view.php
<?php
use yii\helpers\Html;
$colors = ['red','green','orange','blue','purple'];
?>
    <div class="tile <?= $colors[$index%5] ?>">
        <?php //echo '$key: '.$key.', $index: '.$index.', mod 4: '.($index%4).'<br />'; ?>
        <h3 class="title"><?= $model->status>0 ? '<span class="glyphicon glyphicon-export" title="'.Yii::t('docvault','Currently checked out').'"></span>&nbsp;' : '' ?><?= Html::encode($model->description) ?></h3>
        <?= Html::a('&raquo; ' . Html::encode($model->realname), ['view', 'id' => $model->id], ['title'=>Yii::t('docvault', 'View document {realname}', ['realname'=>$model->realname])]); ?><br />
        <?= Html::encode(Yii::t('docvault','Category:')).' '.Html::a($model->category->name, ['document-category/view', 'id'=>$model->categoryId], ['title'=>Yii::t('docvault','View documents in category {category}', ['category'=>$model->category->name])]) ?><br />
        <small><?= Html::encode(Yii::t('docvault', 'document created on {created} by {username}', ['created'=>Yii::$app->formatter->asDatetime($model->created), 'username'=>$model->ownedByUser->username])) ?></small>
    </div>

views/document/checkin.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

use app\models\DocumentCategory;

/* @var $this yii\web\View */
/* @var $model app\models\Document */
/* @var $form yii\widgets\ActiveForm */
$this->title = $model->documentId;
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['view', 'id'=>$model->documentId]];
$this->params['breadcrumbs'][] = 'Check In';
?>

<div class="log-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'documentId')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'note')->textarea(['rows' => 6]) ?>

    <?= '' // $form->field($model, 'status')->textInput() ?>
    
    <?= $form->field($model, 'file')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('docvault', 'Check In'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/document/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = Yii::t('docvault', 'Create New Document');
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="document-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/document/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use diggindata\docvault\widgets\TileView;

use yii\helpers\Url;
use yii\grid\GridView;
/* @var $this yii\web\View */
/* @var $searchModel app\models\DocumentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('docvault', 'Documents');
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;

$createLink = ['create'];
if (!empty($_GET['DocumentSearch']['categoryId']))
	$createLink['Document[categoryId]'] = $_GET['DocumentSearch']['categoryId'];

/**
* create action column template depending acces rights
*/
$actionColumnTemplates = [];

if (\Yii::$app->user->can('app_sheet_view', ['route' => true])) {
	$actionColumnTemplates[] = '{view}';
}

if (\Yii::$app->user->can('app_sheet_update', ['route' => true])) {
	$actionColumnTemplates[] = '{update}';
}

if (\Yii::$app->user->can('app_sheet_delete', ['route' => true])) {
	$actionColumnTemplates[] = '{delete}';
}
if (isset($actionColumnTemplates)) {
	$actionColumnTemplate = implode(' ', $actionColumnTemplates);
	$actionColumnTemplateString = $actionColumnTemplate;
} else {
	Yii::$app->view->params['pageButtons'] = Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New'), ['create'], ['class' => 'btn btn-success']);
	$actionColumnTemplateString = "{view} {update} {delete}";
}
$actionColumnTemplateString = '<div class="action-buttons">'.$actionColumnTemplateString.'</div>';
?>

<div class="document-index">

<h1><?= Html::encode($this->title) ?></h1>
<?php echo $this->render('_search', ['model' => $searchModel]); ?>

<p>
	<?= Html::a(Yii::t('docvault', 'Create New Document', ['modelClass' => 'Document']), $createLink, ['class' => 'btn btn-success']) ?>
	<?= Html::a('<span class="glyphicon glyphicon-search"></span> ' . Yii::t('docvault', 'Advanced Search'), '#', ['class' => 'btn btn-primary search-btn']) ?>
</p>

<?php /* echo TileView::widget([
'dataProvider' => $dataProvider,
'itemOptions' => ['class' => 'item col-sm-4'],
'itemView' => function ($model, $key, $index, $widget) {
return $this->render('_view', ['model'=>$model, 'key'=>$key, 'index'=>$index, ]);
},
])*/ ?>

<div class="table-responsive">
	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'pager' => [
			'class' => yii\widgets\LinkPager::className(),
			'firstPageLabel' => Yii::t('cruds', 'First'),
			'lastPageLabel' => Yii::t('cruds', 'Last'),
		],
		'filterModel' => \Yii::$app->user->can('Administrator') ? $searchModel : NULL,
		'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
		'headerRowOptions' => ['class'=>'x'],
		'columns' => [
			[
				'class' => 'yii\grid\ActionColumn',
				'template' => $actionColumnTemplateString,
				'buttons' => [
					'view' => function ($url, $model, $key) {
						$options = [
							'title' => Yii::t('cruds', 'View'),
							'aria-label' => Yii::t('cruds', 'View'),
							'data-pjax' => '0',
						];
						return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, $options);
					}
				],
				'urlCreator' => function($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
					return Url::toRoute($params);
				},
				'contentOptions' => ['nowrap'=>'nowrap']
			],
			//'id',
			//'realname',
								[
									'class' => yii\grid\DataColumn::className(),
									'attribute' => 'realname',
									'label' => 'Document',
									'value' => function ($model) {
											return Html::a($model->realname, ['view-file','id'=>$model->id], ['data-pjax' => 0]);
									},
									'format' => 'raw',
								],
			'description',
			'category.name',
			'ownerId.name',
			'created'
		],]) 
	?>
</div>

<?php                               
$script = <<< JS
$('.search-btn').on('click', function(e) {
    $('.document-search-form').toggle(400);
    return false;
});
JS;
$this->registerJs($script);
// where $position can be View::POS_READY (the default), 
// or View::POS_HEAD, View::POS_BEGIN, View::POS_END
// ?>

views/document/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = Yii::t('docvault', 'Update Document:') . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('docvault', 'Update');
?>
<div class="document-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/document/updatePermissions.php
<?php
// \yii\helpers\BaseVarDumper::dump($permissions, 10, true);

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Permission;
use Da\user\Model\User;

$this->title = Yii::t('docvault', 'Update Document Permissions:');
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $document->id, 'url' => ['view', 'id' => $document->id]];
$this->params['breadcrumbs'][] = Yii::t('docvault', 'Update Permissions');

?>

<h1><?= Html::encode($this->title) ?></h1>

<div class="document-view">

	<?php $form = ActiveForm::begin([
		'id' => 'document-permissions-form',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger',
		'fieldConfig' => [
			'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
			'horizontalCssClasses' => [
				'label' => 'col-sm-2',
				#'offset' => 'col-sm-offset-4',
				'wrapper' => 'col-sm-8',
				'error' => '',
				'hint' => '',
			],
		],
	]);
	?>
	<?php 
	$userOptions = ArrayHelper::map(User::find()->all(), 'id', 'username');
	$userOptions = ArrayHelper::merge([0=>Yii::t('docvault','All Users')], $userOptions);
	// DEBUG yii\helpers\VarDumper::dump($userOptions, 10, true);
	?>

	<?= $form->field($document, 'realname')->textInput(['disabled'=>'disabled']) ?>

	<?= $form->field($model, 'viewUsers')->dropDownList($userOptions, ['multiple'=>'multiple']); ?>

	<?= $form->field($model, 'modifyUsers')->dropDownList($userOptions, ['multiple'=>'multiple']); ?>


	<?= Html::submitButton(Yii::t('docvault', 'Update'), ['class' => 'btn btn-success']) ?>


	<?php ActiveForm::end(); ?>

</div>

views/document/view.php
<?php

use yii\bootstrap\ButtonGroup;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Document */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'DocVault', 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('docvault', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="document-view">


	<h1><?= Html::encode($this->title) ?></h1>


	<?php echo ($model->mayView) ? Html::a('<span class="glyphicon glyphicon-search"></span> '.Yii::t('docvault', 'View'), ['view-file', 'id' => $model->id], ['class' => 'btn btn-info']) : '' ?>
	<?php echo ($model->status==0 and $model->mayModify) ? Html::a('<span class="glyphicon glyphicon-export"></span> '.Yii::t('docvault', 'Check Out'), ['checkout', 'id' => $model->id], ['class' => 'btn btn-success']) : '' ?>
	<?php echo ($model->status==Yii::$app->user->id) ? Html::a('<span class="glyphicon glyphicon-import"></span> '.Yii::t('docvault', 'Check In'), ['checkin', 'id' => $model->id], ['class' => 'btn btn-success']) : '' ?>
	<?php echo ($model->status==0 and $model->mayModify) ? Html::a('<span class="glyphicon glyphicon-pencil"></span> '.Yii::t('docvault', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) : '' ?>
	<?php echo ($model->status==0 and $model->mayModify) ? Html::a('<span class="glyphicon glyphicon-pencil"></span> '.Yii::t('docvault', 'Permissions'), ['update-permissions', 'id' => $model->id], ['class' => 'btn btn-primary']) : '' ?>
	<?php echo ($model->ownerId == Yii::$app->user->id or $model->mayModify) ? Html::a('<span class="glyphicon glyphicon-remove"></span> ' . Yii::t('docvault', 'Delete'), ['delete', 'id' => $model->id], [
		'class' => 'btn btn-danger',
		'data' => [
			'confirm' => Yii::t('docvault', 'Are you sure you want to delete this item?'),
			'method' => 'post',
		],
	]) : '' ?>

	<?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>


	<?php echo yii\bootstrap\Tabs::widget([
		'items' => [
			[
				'label' => Yii::t('docvault','File'),
				'content' => $this->render('_meta', ['model'=>$model]),
				'active' => true
			],
			[
				'label' => Yii::t('docvault','History'),
				'content' => $this->render('_logs', ['model'=>$model]),
			],
			[
				'label' => Yii::t('docvault', 'Permissions'),
				'content' => $this->render('_permissions', ['model'=>$model]),
			],
		],
	]); ?>

</div>

<?php \yii\widgets\Pjax::end(); ?>


